export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const SET_ACTIVE_PREFERENCE = 'SET_ACTIVE_PREFERENCE';
export const REMOVE_PREFERENCE = 'REMOVE_PREFERENCE';
export const SELECT_OPTION = 'SELECT_OPTION';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const UPDATE_IMG = 'UPDATE_IMG';
